"use client";

import { useState, useEffect } from "react";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export const dictionary = {
  id: {
    // Navbar
    nav_home: "Beranda",
    nav_dashboard: "Dashboard",
    nav_booking: "Pesan Penitipan",
    nav_profile: "Profil Saya",
    nav_login: "Masuk",
    nav_register: "Daftar",
    nav_logout: "Keluar",

    // Hero Section
    hero_badge: "Hotel Kucing Bintang 5 Pertama di Kota Anda",
    hero_title_1: "Penitipan Terbaik untuk Kucing Kesayangan Anda, ",
    hero_title_2: "Penuh Kasih Sayang.",
    hero_desc: "Kami memahami kucing Anda adalah keluarga. NekoStay menghadirkan layanan penitipan kucing online premium dengan laporan berkala, ruang ber-AC, nutrisi terbaik, dan layanan kesehatan siaga.",
    hero_cta_primary: "Pesan Penitipan Sekarang",
    hero_cta_secondary: "Lihat Fasilitas & Tarif",
    hero_stat_cats: "Kucing Terlayani",
    hero_stat_rating: "Rating Kepuasan",
    hero_stat_vet: "Dokter Hewan Siaga",

    // Why Choose Us
    why_title: "Mengapa Memilih NekoStay?",
    why_desc: "Kami berkomitmen menjaga kenyamanan, keamanan, dan keceriaan kucing Anda selama Anda bepergian.",
    why_safe_title: "Keamanan & Higienitas Terjamin",
    why_safe_desc: "Setiap kandang dan area bermain dibersihkan menggunakan disinfektan ramah hewan secara berkala untuk mencegah bakteri dan virus.",
    why_report_title: "Laporan Berkala 2 Hari Sekali",
    why_report_desc: "Dapatkan notifikasi dan email berisi status kesehatan, nafsu makan, dan foto terbaru si mpus yang diupdate langsung oleh staf kami.",
    why_staff_title: "Staf Ahli Penyayang Kucing",
    why_staff_desc: "Staf kami terlatih dalam menangani berbagai karakter kucing, mulai dari yang pemalu hingga yang hiperaktif, dengan kelembutan penuh.",

    // Room Selection
    room_title: "Pilih Kelas Penitipan",
    room_desc: "Beragam pilihan kelas yang dirancang khusus menyesuaikan kenyamanan kucing kesayangan Anda.",
    room_popular: "Paling Populer",
    room_select: "Pilih Kelas",
    room_per_day: "/hari",

    // Booking page / form
    book_title: "Buat Pemesanan Baru",
    book_step_1: "Data Kucing",
    book_step_2: "Pemesanan",
    book_step_3: "Review",
    book_cat_name: "Nama Kucing",
    book_cat_gender: "Jenis Kelamin",
    book_cat_gender_m: "Jantan",
    book_cat_gender_f: "Betina",
    book_cat_age: "Umur Kucing (misal: 1 Tahun, 6 Bulan)",
    book_cat_health: "Status Kesehatan",
    book_cat_health_healthy: "Sehat",
    book_cat_health_sick: "Sakit",
    book_cat_health_med: "Dalam Pengobatan",
    book_cat_food: "Makanan Favorit (Opsional)",
    book_cat_pregnant: "Kucing Sedang Hamil?",
    book_cat_notes: "Catatan Khusus Kucing (Opsional)",
    book_cat_photo: "Foto Kucing",
    book_class_select: "Pilih Kelas Kamar",
    book_checkin: "Tanggal Check-in",
    book_checkout: "Tanggal Check-out",
    book_price_preview: "Preview Harga",
    book_discount_referral: "Diskon Referral",
    book_total_days: "Total Hari",
    book_total_price: "Total Biaya",
    book_referral_code_optional: "Kode Referral (Opsional - Dapatkan Diskon 10%)",
    book_referral_valid: "Kode referral valid! Anda menghemat 10%.",
    book_referral_invalid: "Kode referral tidak valid.",
    book_referral_applying: "Memverifikasi...",
    book_btn_next: "Lanjutkan",
    book_btn_prev: "Kembali",
    book_btn_submit: "Konfirmasi & Pesan Sekarang",

    // Profile page / Referral
    ref_title: "Program Referral NekoStay",
    ref_desc: "Bagikan kode referral Anda ke teman-teman pecinta kucing! Saat mereka mendaftar menggunakan kode Anda, mereka akan mendapatkan diskon 10% pada booking pertama mereka, dan Anda akan mengumpulkan Poin Reward!",
    ref_your_code: "Kode Referral Anda",
    ref_copy_success: "Kode berhasil disalin!",
    ref_stats_title: "Statistik Referral Anda",
    ref_stats_joined: "Teman yang Bergabung",
    ref_stats_points: "Poin Referral",
    ref_stats_points_desc: "1 Poin = Potongan Rp 15,000",
    ref_no_friends: "Belum ada teman yang bergabung menggunakan kode Anda. Yuk bagikan sekarang!",

    // Sidebar / Navigation
    side_panel_admin: "Panel Admin",
    side_admin_title: "NekoStay Admin",
    side_overview: "Overview",
    side_all_bookings: "Semua Pesanan",
    side_cat_conditions: "Kondisi Kucing",
    side_customer_reviews: "Ulasan Pelanggan",
    side_rates_settings: "Kelas & Tarif",
    tab_home: "Beranda",
    tab_bookings: "Pesanan",
    tab_notif: "Notif",
    tab_profile: "Profil",

    // User Dashboard
    user_db_badge: "Dashboard Pemilik",
    user_db_title: "Pesanan Penitipan Saya",
    user_db_subtitle: "Pantau kondisi dan riwayat menginap kucing kesayangan Anda.",
    user_db_new_booking: "Pesan Baru",
    user_db_stat_total: "Total Penitipan",
    user_db_stat_active: "Kucing Menginap",
    user_db_stat_pending: "Menunggu Approval",
    user_db_stat_completed: "Selesai",
    user_db_tab_all: "Semua",
    user_db_tab_waiting: "Menunggu",
    user_db_tab_active: "Aktif",
    user_db_tab_completed: "Selesai",
    user_db_tab_cancelled: "Dibatalkan",
    user_db_no_bookings: "Belum ada pesanan.",
    user_db_no_bookings_desc: "Anda belum pernah melakukan pemesanan penitipan.",

    // Notifications Page
    notif_title: "Kotak Masuk Notifikasi",
    notif_desc: "Lihat riwayat pembaruan status dan laporan kucing Anda.",
    notif_mark_read: "Tandai Semua Dibaca",
    notif_empty: "Kotak Masuk Kosong",
    notif_empty_desc: "Anda belum menerima notifikasi apapun saat ini.",

    // Admin Dashboard
    admin_db_badge: "Data Real-time & Analitik",
    admin_db_title: "Dashboard Admin NekoStay",
    admin_db_subtitle: "Pantau statistik harian, kelola persetujuan masuk, serta pantau gateway notifikasi.",
    admin_db_stat_active: "Kucing Dititipkan",
    admin_db_stat_pending: "Menunggu Persetujuan",
    admin_db_stat_revenue: "Omzet Aktif Bulan Ini",
    admin_db_stat_rating: "Rata-rata Rating",
    admin_db_chart_title: "Statistik & Kinerja Hotel",
    admin_db_chart_revenue: "Pendapatan Hari Ini",
    admin_db_chart_class: "Keterisian Kelas Room",
    admin_db_chart_status: "Status Distribusi Pesanan",
    admin_db_table_title: "Pengajuan Booking Terbaru",
    admin_db_table_empty: "Belum ada pengajuan booking baru.",
    admin_db_shortcut_title: "Pintasan Cepat",
    admin_db_shortcut_bookings: "Proses Persetujuan Booking",
    admin_db_shortcut_reports: "Tulis Laporan Kucing Harian",
    admin_db_shortcut_settings: "Konfigurasi Tarif & Layanan",
    admin_db_gateway_title: "Notification Gateway",
    admin_db_gateway_all: "Semua Notifikasi",
    admin_db_gateway_wa: "WhatsApp Notifikasi",
    admin_db_gateway_system: "Notifikasi Sistem",
    admin_db_gateway_empty: "Belum ada notifikasi keluar yang terkirim di sistem outbox.",
    admin_db_gateway_status: "Terkirim",
    admin_db_gateway_recipient: "Penerima",
    admin_db_view_all: "Lihat Semua",
    admin_db_recent_bookings: "Pemesanan Terbaru",
    admin_db_no_bookings: "Belum ada pemesanan masuk.",
    admin_db_col_cat_owner: "Pemilik & Kucing",
    admin_db_col_class_time: "Kelas & Waktu",
    admin_db_col_total: "Total Estimasi",
    admin_db_col_status: "Status",
    admin_db_chart_trend: "Tren Pendapatan (6 Bulan Terakhir)",
    admin_db_chart_dist: "Distribusi Kelas & Status (Semua Waktu)",
    admin_bookings_badge: "Pemberitahuan & Persetujuan",
    admin_bookings_title: "Semua Pesanan Penitipan",
    admin_bookings_subtitle: "Konfirmasi pengajuan check-in, setujui penolakan, serta lakukan kalkulasi tagihan check-out.",
    admin_bookings_export_pdf: "Ekspor PDF",
    admin_bookings_refresh: "Refresh Data",
    admin_bookings_search_placeholder: "Cari kucing atau pemilik...",
    admin_bookings_class_label: "Kelas Room:",
    admin_bookings_tab_all: "Semua",
    admin_bookings_tab_pending: "Menunggu",
    admin_bookings_tab_active: "Aktif",
    admin_bookings_tab_completed: "Selesai",
    admin_bookings_tab_cancelled: "Dibatalkan",
    admin_bookings_empty: "Tidak ada pesanan.",
    admin_bookings_col_owner_cat: "Pemilik & Kucing",
    admin_bookings_col_class_rate: "Kelas & Tarif",
    admin_bookings_col_schedule: "Durasi Jadwal",
    admin_bookings_col_est_total: "Estimasi Biaya",
    admin_bookings_col_status: "Status",
    admin_bookings_col_action: "Aksi",
    admin_bookings_btn_detail: "Detail",
    admin_bookings_btn_approve: "Setuju",
    admin_bookings_btn_reject: "Tolak",
    admin_bookings_btn_checkout: "Check-out",

    // Admin Reports
    admin_rep_badge: "Kondisi Harian",
    admin_rep_title: "Laporan Kondisi Kucing",
    admin_rep_subtitle: "Pantau seluruh riwayat rekam kondisi harian kucing yang sedang aktif menginap.",
    admin_rep_search: "Cari nama kucing, pemilik, atau isi catatan...",
    admin_rep_empty: "Tidak ada laporan.",
    admin_rep_empty_desc: "Belum ada laporan kondisi harian kucing yang sesuai dengan pencarian Anda.",
    admin_rep_owner: "Pemilik: ",
    admin_rep_detail: "Detail Booking",

    // Admin Reviews
    admin_rev_badge: "Manajemen Ulasan",
    admin_rev_title: "Ulasan & Testimoni Pelanggan",
    admin_rev_subtitle: "Lihat feedback dari pelanggan dan balas ulasan secara langsung melalui email.",
    admin_rev_empty: "Belum ada ulasan yang masuk dari pelanggan.",
    admin_rev_cat: "Kucing: ",
    admin_rev_no_text: "Tidak ada ulasan tertulis.",
    admin_rev_response_title: "Tanggapan Admin NekoStay:",
    admin_rev_reply_email: "Kirim Balasan via Email",
    admin_rev_reply_placeholder: "Tulis balasan Anda ke email pelanggan...",
    admin_rev_btn_cancel: "Batal",
    admin_rev_btn_sending: "Mengirim...",
    admin_rev_btn_send: "Kirim",
    admin_rev_btn_detail: "Detail Pesanan",
    admin_rev_btn_reply: "Balas Review",
    admin_rev_btn_edit: "Ubah Balasan",
    admin_rev_load_failed: "Gagal memuat daftar ulasan pelanggan.",
    admin_rev_reply_success: "Balasan ulasan berhasil dikirim via email dan disimpan!",
    admin_rev_reply_failed: "Gagal mengirim balasan.",

    // Admin Settings
    admin_set_badge: "Pengaturan Sistem",
    admin_set_title: "Tarif & Kelas Penitipan",
    admin_set_subtitle: "Sesuaikan tarif harian masing-masing kelas penitipan kucing yang ditawarkan.",
    admin_set_rate_label: "Tarif Harian (Rupiah)",
    admin_set_rate_placeholder: "Masukkan tarif baru",
    admin_set_fac_title: "Fasilitas Kelas",
    admin_set_btn_save: "Perbarui Tarif",
    admin_set_btn_saving: "Menyimpan...",
    admin_set_info_title: "Keterangan Tarif & Tagihan",
    admin_set_info_desc: "Pembaruan tarif harian di atas hanya akan berlaku untuk pemesanan baru yang diajukan setelah perubahan disimpan. Pemesanan yang sedang berjalan (Aktif) atau sedang menunggu konfirmasi (Menunggu) akan tetap menggunakan tarif lama yang terdaftar saat pemesanan dibuat demi kenyamanan pelanggan.",
    admin_set_err_positive: "Tarif harus berupa angka positif.",
    admin_set_err_failed: "Gagal memperbarui tarif.",

    // Shared Pagination
    pager_showing: "Menampilkan",
    pager_of: "dari",
    pager_reports: "laporan",
    pager_reviews: "ulasan",

    // Cat Health Statuses
    status_healthy: "Sehat",
    status_unwell: "Kurang Fit",
    status_sick: "Sakit",
  },
  en: {
    // Navbar
    nav_home: "Home",
    nav_dashboard: "Dashboard",
    nav_booking: "Book a Stay",
    nav_profile: "My Profile",
    nav_login: "Login",
    nav_register: "Register",
    nav_logout: "Logout",

    // Hero Section
    hero_badge: "The First 5-Star Cat Hotel in Your Town",
    hero_title_1: "The Best Boarding for Your Beloved Cat, ",
    hero_title_2: "Full of Care & Love.",
    hero_desc: "We understand your cat is family. NekoStay provides premium online cat boarding services with regular reports, AC rooms, top-tier nutrition, and standby veterinary services.",
    hero_cta_primary: "Book a Stay Now",
    hero_cta_secondary: "View Facilities & Rates",
    hero_stat_cats: "Cats Served",
    hero_stat_rating: "Satisfaction Rating",
    hero_stat_vet: "Vets on Standby",

    // Why Choose Us
    why_title: "Why Choose NekoStay?",
    why_desc: "We are committed to keeping your cat comfortable, safe, and happy while you travel.",
    why_safe_title: "Guaranteed Safety & Hygiene",
    why_safe_desc: "Every cage and play area is regularly disinfected with pet-friendly solutions to prevent bacteria and viruses.",
    why_report_title: "Bi-daily Status Reports",
    why_report_desc: "Get notifications and emails containing health status, appetite, and the latest photos of your cat updated directly by our staff.",
    why_staff_title: "Professional Cat-loving Staff",
    why_staff_desc: "Our staff is highly trained in handling various cat personalities, from shy to hyperactive, with total gentleness.",

    // Room Selection
    room_title: "Choose a Boarding Class",
    room_desc: "A wide variety of class choices designed specifically to match your beloved cat's comfort.",
    room_popular: "Most Popular",
    room_select: "Select Class",
    room_per_day: "/day",

    // Booking page / form
    book_title: "Create a New Booking",
    book_step_1: "Cat Data",
    book_step_2: "Booking Details",
    book_step_3: "Review",
    book_cat_name: "Cat's Name",
    book_cat_gender: "Gender",
    book_cat_gender_m: "Male",
    book_cat_gender_f: "Female",
    book_cat_age: "Cat's Age (e.g. 1 Year, 6 Months)",
    book_cat_health: "Health Status",
    book_cat_health_healthy: "Healthy",
    book_cat_health_sick: "Sick",
    book_cat_health_med: "Under Medication",
    book_cat_food: "Favorite Food (Optional)",
    book_cat_pregnant: "Is Your Cat Pregnant?",
    book_cat_notes: "Special Notes for Cat (Optional)",
    book_cat_photo: "Cat's Photo",
    book_class_select: "Choose Stay Class",
    book_checkin: "Check-in Date",
    book_checkout: "Check-out Date",
    book_price_preview: "Price Preview",
    book_discount_referral: "Referral Discount",
    book_total_days: "Total Days",
    book_total_price: "Total Cost",
    book_referral_code_optional: "Referral Code (Optional - Save 10%)",
    book_referral_valid: "Referral code valid! You saved 10%.",
    book_referral_invalid: "Invalid referral code.",
    book_referral_applying: "Verifying...",
    book_btn_next: "Next",
    book_btn_prev: "Back",
    book_btn_submit: "Confirm & Book Now",

    // Profile page / Referral
    ref_title: "NekoStay Referral Program",
    ref_desc: "Share your referral code with fellow cat lovers! When they register using your code, they get a 10% discount on their first booking, and you accumulate Reward Points!",
    ref_your_code: "Your Referral Code",
    ref_copy_success: "Code copied successfully!",
    ref_stats_title: "Your Referral Statistics",
    ref_stats_joined: "Friends Joined",
    ref_stats_points: "Referral Points",
    ref_stats_points_desc: "1 Point = Rp 15,000 Discount",
    ref_no_friends: "No friends have joined using your code yet. Share it now!",

    // Sidebar / Navigation
    side_panel_admin: "Admin Panel",
    side_admin_title: "NekoStay Admin",
    side_overview: "Overview",
    side_all_bookings: "All Bookings",
    side_cat_conditions: "Cat Conditions",
    side_customer_reviews: "Customer Reviews",
    side_rates_settings: "Classes & Rates",
    tab_home: "Home",
    tab_bookings: "Bookings",
    tab_notif: "Alerts",
    tab_profile: "Profile",

    // User Dashboard
    user_db_badge: "Owner Dashboard",
    user_db_title: "My Boarding Bookings",
    user_db_subtitle: "Monitor the condition and stay history of your beloved cat.",
    user_db_new_booking: "New Booking",
    user_db_stat_total: "Total Stays",
    user_db_stat_active: "Active Stays",
    user_db_stat_pending: "Waiting Approval",
    user_db_stat_completed: "Completed Stays",
    user_db_tab_all: "All",
    user_db_tab_waiting: "Waiting",
    user_db_tab_active: "Active",
    user_db_tab_completed: "Completed",
    user_db_tab_cancelled: "Cancelled",
    user_db_no_bookings: "No bookings yet.",
    user_db_no_bookings_desc: "You haven't made any boarding bookings yet.",

    // Notifications Page
    notif_title: "Notifications Inbox",
    notif_desc: "View history of status updates and reports for your cat.",
    notif_mark_read: "Mark All Read",
    notif_empty: "Inbox Empty",
    notif_empty_desc: "You have not received any notifications at this time.",

    // Admin Dashboard
    admin_db_badge: "Real-time Data & Analytics",
    admin_db_title: "NekoStay Admin Dashboard",
    admin_db_subtitle: "Monitor daily stats, manage check-in approvals, and track outbox gateway.",
    admin_db_stat_active: "Cats Boarded",
    admin_db_stat_pending: "Pending Approvals",
    admin_db_stat_revenue: "Active Revenue This Month",
    admin_db_stat_rating: "Average Rating",
    admin_db_chart_title: "Hotel Performance & Stats",
    admin_db_chart_revenue: "Today's Revenue",
    admin_db_chart_class: "Room Class Occupancy",
    admin_db_chart_status: "Booking Distribution Status",
    admin_db_table_title: "Recent Booking Submissions",
    admin_db_table_empty: "No new booking requests yet.",
    admin_db_shortcut_title: "Quick Shortcuts",
    admin_db_shortcut_bookings: "Process Booking Approvals",
    admin_db_shortcut_reports: "Write Daily Cat Reports",
    admin_db_shortcut_settings: "Rates & Services Config",
    admin_db_gateway_title: "Notification Gateway",
    admin_db_gateway_all: "All Notifications",
    admin_db_gateway_wa: "WhatsApp Notifications",
    admin_db_gateway_system: "System Notifications",
    admin_db_gateway_empty: "No outgoing notifications sent in the outbox system.",
    admin_db_gateway_status: "Sent",
    admin_db_gateway_recipient: "Recipient",
    admin_db_view_all: "View All",
    admin_db_recent_bookings: "Recent Bookings",
    admin_db_no_bookings: "No incoming bookings yet.",
    admin_db_col_cat_owner: "Owner & Cat",
    admin_db_col_class_time: "Class & Time",
    admin_db_col_total: "Total Est",
    admin_db_col_status: "Status",
    admin_db_chart_trend: "Revenue Trend (Last 6 Months)",
    admin_db_chart_dist: "Class & Status Distribution (All Time)",
    admin_bookings_badge: "Alerts & Approvals",
    admin_bookings_title: "All Boarding Bookings",
    admin_bookings_subtitle: "Confirm check-in submissions, approve rejections, and calculate check-out invoices.",
    admin_bookings_export_pdf: "Export PDF",
    admin_bookings_refresh: "Refresh Data",
    admin_bookings_search_placeholder: "Search cats or owners...",
    admin_bookings_class_label: "Room Class:",
    admin_bookings_tab_all: "All",
    admin_bookings_tab_pending: "Pending",
    admin_bookings_tab_active: "Active",
    admin_bookings_tab_completed: "Completed",
    admin_bookings_tab_cancelled: "Cancelled",
    admin_bookings_empty: "No bookings found.",
    admin_bookings_col_owner_cat: "Owner & Cat",
    admin_bookings_col_class_rate: "Class & Rate",
    admin_bookings_col_schedule: "Duration Schedule",
    admin_bookings_col_est_total: "Estimated Cost",
    admin_bookings_col_status: "Status",
    admin_bookings_col_action: "Action",
    admin_bookings_btn_detail: "Detail",
    admin_bookings_btn_approve: "Approve",
    admin_bookings_btn_reject: "Reject",
    admin_bookings_btn_checkout: "Check-out",

    // Admin Reports
    admin_rep_badge: "Daily Condition",
    admin_rep_title: "Cat Condition Reports",
    admin_rep_subtitle: "Monitor the entire daily condition record history of cats currently boarding.",
    admin_rep_search: "Search cat name, owner, or notes...",
    admin_rep_empty: "No reports found.",
    admin_rep_empty_desc: "There are no daily condition reports matching your search.",
    admin_rep_owner: "Owner: ",
    admin_rep_detail: "Booking Details",

    // Admin Reviews
    admin_rev_badge: "Review Management",
    admin_rev_title: "Customer Reviews & Testimonials",
    admin_rev_subtitle: "View customer feedback and reply to reviews directly via email.",
    admin_rev_empty: "No customer reviews received yet.",
    admin_rev_cat: "Cat: ",
    admin_rev_no_text: "No written review.",
    admin_rev_response_title: "NekoStay Admin Response:",
    admin_rev_reply_email: "Send Reply via Email",
    admin_rev_reply_placeholder: "Write your reply to the customer's email...",
    admin_rev_btn_cancel: "Cancel",
    admin_rev_btn_sending: "Sending...",
    admin_rev_btn_send: "Send",
    admin_rev_btn_detail: "Order Details",
    admin_rev_btn_reply: "Reply Review",
    admin_rev_btn_edit: "Edit Reply",
    admin_rev_load_failed: "Failed to load customer reviews list.",
    admin_rev_reply_success: "Review reply successfully sent via email and saved!",
    admin_rev_reply_failed: "Failed to send reply.",

    // Admin Settings
    admin_set_badge: "System Settings",
    admin_set_title: "Rates & Boarding Classes",
    admin_set_subtitle: "Adjust the daily rate for each cat boarding class offered.",
    admin_set_rate_label: "Daily Rate (Rupiah)",
    admin_set_rate_placeholder: "Enter new rate",
    admin_set_fac_title: "Class Facilities",
    admin_set_btn_save: "Update Rate",
    admin_set_btn_saving: "Saving...",
    admin_set_info_title: "Rate & Billing Information",
    admin_set_info_desc: "Updates to the daily rates above will only apply to new bookings submitted after the changes are saved. Ongoing bookings (Active) or those awaiting confirmation (Pending) will still use the old rate registered when the booking was made for customer convenience.",
    admin_set_err_positive: "Rate must be a positive number.",
    admin_set_err_failed: "Failed to update rate.",

    // Shared Pagination
    pager_showing: "Showing",
    pager_of: "of",
    pager_reports: "reports",
    pager_reviews: "reviews",

    // Cat Health Statuses
    status_healthy: "Healthy",
    status_unwell: "Unwell",
    status_sick: "Sick",
  },
};

const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: "id",
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return dictionary[lang]?.[key] || key;
      },
    }),
    {
      name: "nekostay-language",
    }
  )
);

export function useLanguage() {
  const store = useLanguageStore();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const language = mounted ? store.language : "id";

  return {
    language,
    setLanguage: store.setLanguage,
    t: (key) => {
      return dictionary[language]?.[key] || key;
    },
  };
}

